### ISSUE TITLE
📌 组件单元测试提升计划

### ISSUE THREAD

**Issue by PengYYYYY** [Tencent/tdesign-vue-next#768]
## 说明
本仓库中组件代码有很多与 [vue](https://github.com/Tencent/tdesign-vue/issues/1418) 仓库公用，大部分测试用例代码也能复用，区别在于本仓库用 Vitest 编写用例，[vue](https://github.com/Tencent/tdesign-vue/issues/1418)使用 Jest 写用例。
因此建议认领的同学同时负责 vue2 与 vue next 两个仓库中对应组件的测试用例编写任务，如果你更熟悉 Jest 可以参照 [官方迁移指南](https://cn.vitest.dev/guide/migration.html) 来学习如何使用 Vitest。
1. 遵循 [TDesign 单元测试规范](https://github.com/Tencent/tdesign-vue-next/wiki/TDesign-%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%E8%A7%84%E8%8C%83) 进行单测开发，文档持续更新
2. 参与贡献请在此 `issue` 中评论领取的组件
3. 领取后请在两周内提交单元测试代码，单测过程中发现组件问题可以提 `issue` 或在 `PR` 中修复
4. 提交 PR 前请先本地确认该组件行、函数覆盖率达80%+

⚠️ 重要：尽量开发一些有难度的、带边界校验的组件测试用例，以复杂组件为主。因为后面  Vue2/Vue3/React 会持续会统一自动生成测试用例。（统一通过 tdesign-api 输出测试用例，如果对这个有兴趣的可以联系 @chaishi ）

### 基础

* [x] `button` @chaishi #2219
* [x] `icon` - @LadyChatterleyLover #1925
* [x] `link` @chaishi #2219

### 布局

* [x] `divider` @chaishi  #2225
* [x] `grid` - @LadyChatterleyLover #1755
* [x] `layout` - @LadyChatterleyLover #1760
* [x] `space` - @LadyChatterleyLover #1920

###  导航

* [x] `affix` - #775
* [x] `anchor`  - #2043
* [x] `breadcrumb` -@xxxlj  #1459
* [x] `dropdown` - @Isabella327 #1708
* [x] `jumper` - @LadyChatterleyLover #1921
* [x] `menu` - @LeeJim 
* [x] `dropdown` - @Isabella327 #1708
* [x] `pagination` - @HelKyle  #1690
* [x] `steps` - @LadyChatterleyLover #1813
* [x] `tabs` - @YunYouJun #1734

### 输入

* [x] `AutoComplete` @chaishi #2219
* [x] `cascader ` - @pengYYYYY - #2043
* [x] `checkbox`- @LadyChatterleyLover #1781
* [x] `color-picker` - @S-mohan #1872
* [x] `date-picker`  - @HQ-Lin 
* [x] `form` - @k1nz 
* [x] `input`- @LadyChatterleyLover #1764  @chaishi  #1764 
* [x] `input-number` -  @LadyChatterleyLover #1816
* [x] `radio`- @LadyChatterleyLover #1778      @chaishi #2241
* [x] `select` - @pengYYYYY - #2043
* [ ] `select-input` - @whitexie - #2291
* [x] `slider` - @ChrisLee0211 #1141
* [x] `switch`- @ChrisLee0211 #1729
* [x] `tag-input` - @LadyChatterleyLover #1865 @chaishi #2357
* [x] `textarea`- @LadyChatterleyLover #1772
* [x] `transfer` - @LadyChatterleyLover #1862
* [x] `time-picker` @uyarn  https://github.com/Tencent/tdesign-vue-next/pull/1979
* [x] `tree-select`
* [x] `upload` @chaishi https://github.com/Tencent/tdesign-vue-next/pull/2418

### 数据展示

* [x]  `avatar` - @LadyChatterleyLover #1753 @chaishi #2404
* [x]  `badge`- @LadyChatterleyLover  #1746
* [x] `calendar` - @PsTiu  #1972
* [x] `card` - @LadyChatterleyLover
* [x] `collapse `  - @isanxia
* [x] `comment`  - @LadyChatterleyLover #1785
* [x] `image` - @LadyChatterleyLover #1922   @chaishi https://github.com/Tencent/tdesign-vue-next/pull/2342
* [ ] `imageViewer`
* [x] `list`  - @LadyChatterleyLover #1788
* [x] `loading` - @LadyChatterleyLover #1789
* [x] `progress` - @LadyChatterleyLover #1783
* [x] `skeleton`  - @LadyChatterleyLover #1744
* [x] `swiper`  - @duenyang
* [x] `table`  - @chaishi  
* [x] `tag` - @LadyChatterleyLover #1743 @chaishi #2349
* [x] `tooltip` - @LadyChatterleyLover #1849 
* [x] `tree` - @pengYYYYY 
* [x] `watermark`
* [x] `rate`- @whitexie - #2336
* [X] `timeline` @chaishi https://github.com/Tencent/tdesign-vue-next/pull/2395

### 消息提醒

* [x] `alert` - @LadyChatterleyLover #1786
* [x] `dialog` -  @LadyChatterleyLover #1811
* [x] `drawer` -  @LadyChatterleyLover #1833
* [x] `guide` - @chaishi #2363
* [x] `message` - @LadyChatterleyLover #1824
* [x] `notification` - @jiazengp - #2043
* [x] `pop-confirm`- @Dlame
* [x] `popup` - @byq1213

**Comment by ChrisLee0211** [comment]
认领slider

**Comment by n1203** [comment]
认领 alert

**Comment by ontheroad1992** [comment]
认领 affix

**Comment by xxxlj** [comment]
认领breadcrumb

**Comment by LadyChatterleyLover** [comment]
认领grid， layout，checkbox，radio, switch, input,textarea, avatar, badge, card,progress, skeleton, tag

**Comment by HelKyle** [comment]
认领 jumper

**Comment by jiazengp** [comment]
认领 ` notification` @pengYYYYY

**Comment by Isabella327** [comment]
认领dropdown

**Comment by duenyang** [comment]
认领swiper

**Comment by ChrisLee0211** [comment]
认领switch

**Comment by HelKyle** [comment]
认领 pagination

**Comment by isanxia** [comment]
认领collapse

**Comment by Dlame** [comment]
认领`pop-confirm`

**Comment by k1nz** [comment]
认领 `form`

**Comment by LadyChatterleyLover** [comment]
认领comment，list，alert，steps

**Comment by LadyChatterleyLover** [comment]
认领loading

**Comment by LeeJim** [comment]
认领 menu

**Comment by byq1213** [comment]
认领 Message, Tooltip, Popup

**Comment by LadyChatterleyLover** [comment]
认领transfer

**Comment by LadyChatterleyLover** [comment]
认领tag-input

**Comment by pengYYYYY** [comment]
> 认领 Message, Tooltip, Popup

popup 分配给你了，其他两个已经处理完了

**Comment by LadyChatterleyLover** [comment]
认领jumper，space，icon，image

**Comment by whitexie** [comment]
认领 select-input

**Comment by whitexie** [comment]
认领 rate

**Comment by zhangjiaoalice** [comment]
认领 imageViewer
